apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "homework-app.labels" . | nindent 4 }}
data:
  app.name: {{ .Values.app.name | quote }}
  app.version: {{ .Values.app.version | quote }}
  log.level: {{ .Values.app.logLevel | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "homework-app.labels" . | nindent 4 }}
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }

    http {
        server {
            listen {{ .Values.service.port }};
            server_name localhost;

            location /conf/file {
                alias /homework/conf/;
                autoindex on;
                disable_symlinks off;

                # Добавляем "/" в конце URL, если его нет
                if (-d $request_filename) {
                    rewrite ^(/conf/file)([^/])$ $1$2/ permanent;
                }
            }

            location / {
                root /usr/share/nginx/html;
                index index.html;
            }

            location /homepage {
                alias /usr/share/nginx/html;
                try_files $uri $uri/ /index.html;
            }

            location /metrics.html {
                root /usr/share/nginx/html;
            }
        }
    }