{{- if .Values.storage.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storage.storageClassName }}
  labels:
    {{- include "homework-app.labels" . | nindent 4 }}
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: {{ .Values.storage.reclaimPolicy }}
{{- end }}